# Server Port
server:
  port: '8080'

spring:
  # Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: test
    password: test1234
   
# Actuator
management:
  endpoints:
    enabled-by-default: false